# Generated by Django 3.2.3 on 2021-06-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consig_id', models.CharField(max_length=100)),
                ('consig_name', models.CharField(max_length=100)),
                ('consig_add', models.CharField(max_length=100)),
                ('consig_city', models.CharField(max_length=100)),
                ('consig_state', models.CharField(max_length=100)),
                ('consig_country', models.CharField(max_length=100)),
                ('consig_zip', models.CharField(max_length=100)),
                ('consig_tele', models.CharField(max_length=100)),
                ('consig_email', models.EmailField(max_length=254)),
                ('consig_ext', models.CharField(max_length=100)),
                ('consig_contact', models.IntegerField(max_length=100)),
                ('consig_notes', models.CharField(max_length=100)),
            ],
        ),
    ]
