# Generated by Django 3.2.3 on 2021-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_feedbackt'),
    ]

    operations = [
        migrations.CreateModel(
            name='customert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField()),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_addr', models.CharField(max_length=100)),
                ('cus_city', models.CharField(max_length=100)),
                ('cus_state', models.CharField(max_length=100)),
                ('cus_country', models.CharField(max_length=100)),
                ('cus_zip', models.IntegerField()),
                ('cus_phone', models.IntegerField()),
                ('cus_email', models.EmailField(max_length=254)),
                ('cus_mc', models.CharField(max_length=100)),
                ('cus_notes', models.CharField(max_length=100)),
            ],
        ),
    ]
