# Generated by Django 3.2.3 on 2021-06-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_customert'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispatcht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_id', models.CharField(max_length=100)),
                ('dis_fname', models.CharField(max_length=100)),
                ('dis_lname', models.CharField(max_length=100)),
                ('dis_phone', models.IntegerField()),
                ('dis_email', models.EmailField(max_length=254)),
                ('dis_rate', models.CharField(max_length=100)),
            ],
        ),
    ]
