# Generated by Django 3.2.3 on 2021-06-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_drivert_shippert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippert',
            old_name='cus_addr',
            new_name='ship_addr',
        ),
    ]
