# Generated by Django 3.2.3 on 2021-06-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_equipmentst_load_entryt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load_entryt',
            old_name='load_addr',
            new_name='load_addre',
        ),
    ]
