# Generated by Django 3.2.3 on 2021-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_dri_pay_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=100)),
                ('com_email', models.EmailField(max_length=254)),
                ('com_addr', models.CharField(max_length=200)),
                ('com_phone', models.IntegerField()),
                ('com_cur', models.CharField(max_length=100)),
                ('com_logo', models.FileField(upload_to='')),
            ],
        ),
    ]
