# Generated by Django 3.2.3 on 2021-06-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0015_edit_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='edit_settings',
        ),
    ]
